image: nptemp/neuron-simulation:latest

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - cd ..
    - cmake --build build --target main
  tags:
    - kubernetes

test:
  stage: test
  script:
    - mkdir build_test
    - cd build_test
    - cmake ..
    - cd ..
    - cmake --build build_test --target main_test
    - cmake --build build_test --target test
  tags:
    - kubernetes
