image: nptemp/neuron-simulation:latest

build:
  stage: build
  script:
    - cmake --target main
  tags:
    - kubernetes

test:
  stage: test
  script:
    - cmake --target test
  tags:
      - kubernetes
