image: docker:latest

# When using dind (Docker in Docker), it's wise to use the overlayfs driver for improved performance.
variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME_AND_TAG: my-docker-hub/$CI_PROJECT_ID:$CI_BUILD_REF_NAME_test

services:
  - docker:dind

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN my-docker-hub
  - docker build -t runtime-env-image:latest .
  - docker push IMAGE_NAME_AND_TAG

build:
  stage: build
  image: $IMAGE_NAME_AND_TAG
  script:
    - cmake --target main

test:
  stage: test
  image: $IMAGE_NAME_AND_TAG
  script:
    - cmake --target test
