image: rhneuroprocessor/neuro-simulation-env:2.0.0-dev_01

variables:
    MAIN_NAME: "parallel-neuro-sim"
    TEST_SUFFIX: "_test"

stages:
  - build
  - test
  - deploy

build-x86_64:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DUSE_RISCV_DOCKER_PRESETS=OFF -DUSE_OPENMP=ON
    - make ${MAIN_NAME}
    # Some test commands to see if the compiled binary really runs
    - src/${MAIN_NAME} --help
    - rm -rf *
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DUSE_RISCV_DOCKER_PRESETS=OFF -DUSE_OPENMP=OFF
    - make ${MAIN_NAME}
    - src/${MAIN_NAME} --help
    - rm -rf *
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_RISCV_DOCKER_PRESETS=OFF -DUSE_OPENMP=ON
    - make ${MAIN_NAME}
    - src/${MAIN_NAME} --help
    # TODO Find out why this causes segmentation fault
#    - rm -rf *
#    - cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_RISCV_DOCKER_PRESETS=OFF -DUSE_OPENMP=OFF
#    - make ${MAIN_NAME}
#    - src/${MAIN_NAME} --help
  tags:
    - kubernetes-stage

build-riscv:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DUSE_RISCV_DOCKER_PRESETS=ON -DUSE_OPENMP=ON
    - make ${MAIN_NAME}
    # Cannot run the binary yet because it is built for a different target
#    - src/${MAIN_NAME} --help
    - rm -rf *
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DUSE_RISCV_DOCKER_PRESETS=ON -DUSE_OPENMP=OFF
    - make ${MAIN_NAME}
#    - src/${MAIN_NAME} --help
    - rm -rf *
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_RISCV_DOCKER_PRESETS=ON -DUSE_OPENMP=ON
    - make ${MAIN_NAME}
#    - src/${MAIN_NAME} --help
    - rm -rf *
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_RISCV_DOCKER_PRESETS=ON -DUSE_OPENMP=OFF
    - make ${MAIN_NAME}
#    - src/${MAIN_NAME} --help
  tags:
    - kubernetes-stage

test: # Statically linked ${MAIN_NAME}${TEST_SUFFIX} has segmentation fault
  stage: test
  script:
    - mkdir build_test
    - cd build_test
    - cmake .. -DCMAKE_BUILD_TYPE=Debug
    - cd ..
    - cmake --build build_test --target ${MAIN_NAME}${TEST_SUFFIX}
    - build_test/src/${MAIN_NAME}${TEST_SUFFIX} --gtest_filter=* --gtest_color=no
  tags:
    - kubernetes-stage

deploy-omp:
  stage: deploy
  script:
    - mkdir build
    - mkdir release
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_OPENMP=ON
    - make ${MAIN_NAME}
    - mv src/${MAIN_NAME} ../release/neuro-simulation_x86_64_omp_${CI_JOB_ID}_${CI_COMMIT_TAG}
  artifacts:
    paths:
      - release
  tags:
    - kubernetes-stage
  only:
    - tags

deploy-no-omp:
  stage: deploy
  script:
    - mkdir build
    - mkdir release
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_OPENMP=OFF
    - make ${MAIN_NAME}
    - mv src/${MAIN_NAME} ../release/neuro-simulation_x86_64_no_omp_${CI_JOB_ID}_${CI_COMMIT_TAG}
  artifacts:
    paths:
      - release
  tags:
    - kubernetes-stage
  only:
    - tags
