image: rhneuroprocessor/neuro-simulation-env:1.2.1

build-dynamic:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug
    - cd ..
    - cmake --build build --target main
    # Some test commands to see if the compiled binary really runs'
    - build/src/main --help
  tags:
    - kubernetes-stage

build-static:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cd ..
    - cmake --build build --target main
    # Some test commands to see if the compiled binary really runs'
    - build/src/main --help
  tags:
    - kubernetes-stage

test: # Statically linked main_test has segmentation fault
  stage: test
  script:
    - mkdir build_test
    - cd build_test
    - cmake .. -DCMAKE_BUILD_TYPE=Debug
    - cd ..
    - cmake --build build_test --target main_test
    - build_test/src/main_test --gtest_filter=* --gtest_color=no
  tags:
    - kubernetes-stage
