image: rhneuroprocessor/neuro-simulation-env:1.3.0

stages:
  - build
  - test
  - deploy

build-dynamic:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DUSE_OPENMP=ON
    - make parallel-neuro-sim
    # Some test commands to see if the compiled binary really runs
    - src/parallel-neuro-sim --help
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DUSE_OPENMP=OFF
    - make parallel-neuro-sim
    - src/parallel-neuro-sim --help
  tags:
    - kubernetes-stage

build-static:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_OPENMP=ON
    - make parallel-neuro-sim
    # Some test commands to see if the compiled binary really runs
    - src/parallel-neuro-sim --help
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_OPENMP=OFF
    - make parallel-neuro-sim
    - src/parallel-neuro-sim --help
  tags:
    - kubernetes-stage

test: # Statically linked main_test has segmentation fault
  stage: test
  script:
    - mkdir build_test
    - cd build_test
    - cmake .. -DCMAKE_BUILD_TYPE=Debug
    - cd ..
    - cmake --build build_test --target main_test
    - build_test/src/main_test --gtest_filter=* --gtest_color=no
  tags:
    - kubernetes-stage

deploy-omp:
  stage: deploy
  script:
    - mkdir build
    - mkdir release
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_OPENMP=ON
    - make parallel-neuro-sim
    - mv src/parallel-neuro-sim ../release/neuro-simulation_x86_64_omp_${CI_JOB_ID}_${CI_COMMIT_TAG}
  artifacts:
    paths:
      - release
  tags:
    - kubernetes-stage
  only:
    - tags

deploy-no-omp:
  stage: deploy
  script:
    - mkdir build
    - mkdir release
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_OPENMP=OFF
    - make parallel-neuro-sim
    - mv src/parallel-neuro-sim ../release/neuro-simulation_x86_64_no_omp_${CI_JOB_ID}_${CI_COMMIT_TAG}
  artifacts:
    paths:
      - release
  tags:
    - kubernetes-stage
  only:
    - tags
