image: docker.csse.rose-hulman.edu/neuroprocessor-group/parallel-neuro-simulation/neuro-simulation-env:2.2.0

variables:
    MAIN_NAME: "parallel-neuro-sim"
    TEST_SUFFIX: "_test"

stages:
  - build
  - test
  - deploy

build-x86_64:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DUSE_RISCV_DOCKER_PRESETS=OFF -DUSE_OPENMP=ON -DINCLUDE_LUT_SUPPORT=OFF
    - make ${MAIN_NAME}
    # Some test commands to see if the compiled binary really runs
    - src/${MAIN_NAME} --help
    - rm -rf *
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DUSE_RISCV_DOCKER_PRESETS=OFF -DUSE_OPENMP=OFF -DINCLUDE_LUT_SUPPORT=OFF
    - make ${MAIN_NAME}
    - src/${MAIN_NAME} --help
    - rm -rf *
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_RISCV_DOCKER_PRESETS=OFF -DUSE_OPENMP=ON -DINCLUDE_LUT_SUPPORT=OFF
    - make ${MAIN_NAME}
    - src/${MAIN_NAME} --help
    - rm -rf *
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_RISCV_DOCKER_PRESETS=OFF -DUSE_OPENMP=OFF -DINCLUDE_LUT_SUPPORT=OFF
    - make ${MAIN_NAME}
    - src/${MAIN_NAME} --help
    - rm -rf *
  tags:
    - kubernetes

build-riscv:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - mkdir build
    - cd build
    - CC=/riscv/bin/riscv64-unknown-linux-gnu-gcc CXX=/riscv/bin/riscv64-unknown-linux-gnu-g++ cmake .. -DCMAKE_BUILD_TYPE=Debug -DUSE_RISCV_DOCKER_PRESETS=ON -DUSE_OPENMP=ON -DINCLUDE_LUT_SUPPORT=ON
    - make ${MAIN_NAME}
    # Cannot run the binary yet because it is built for a different target
#    - src/${MAIN_NAME} --help
    - rm -rf *
    - CC=/riscv/bin/riscv64-unknown-linux-gnu-gcc CXX=/riscv/bin/riscv64-unknown-linux-gnu-g++ cmake .. -DCMAKE_BUILD_TYPE=Debug -DUSE_RISCV_DOCKER_PRESETS=ON -DUSE_OPENMP=OFF -DINCLUDE_LUT_SUPPORT=ON
    - make ${MAIN_NAME}
#    - src/${MAIN_NAME} --help
    - rm -rf *
    - CC=/riscv/bin/riscv64-unknown-linux-gnu-gcc CXX=/riscv/bin/riscv64-unknown-linux-gnu-g++ cmake .. -DCMAKE_BUILD_TYPE=Debug -DUSE_RISCV_DOCKER_PRESETS=ON -DUSE_OPENMP=ON -DINCLUDE_LUT_SUPPORT=OFF
    - make ${MAIN_NAME}
#    - src/${MAIN_NAME} --help
    - rm -rf *
    - CC=/riscv/bin/riscv64-unknown-linux-gnu-gcc CXX=/riscv/bin/riscv64-unknown-linux-gnu-g++ cmake .. -DCMAKE_BUILD_TYPE=Debug -DUSE_RISCV_DOCKER_PRESETS=ON -DUSE_OPENMP=OFF -DINCLUDE_LUT_SUPPORT=OFF
    - make ${MAIN_NAME}
#    - src/${MAIN_NAME} --help
    - rm -rf *
    - CC=/riscv/bin/riscv64-unknown-linux-gnu-gcc CXX=/riscv/bin/riscv64-unknown-linux-gnu-g++ cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_RISCV_DOCKER_PRESETS=ON -DUSE_OPENMP=ON -DINCLUDE_LUT_SUPPORT=ON
    - make ${MAIN_NAME}
#    - src/${MAIN_NAME} --help
    - rm -rf *
    - CC=/riscv/bin/riscv64-unknown-linux-gnu-gcc CXX=/riscv/bin/riscv64-unknown-linux-gnu-g++ cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_RISCV_DOCKER_PRESETS=ON -DUSE_OPENMP=OFF -DINCLUDE_LUT_SUPPORT=ON
    - make ${MAIN_NAME}
#    - src/${MAIN_NAME} --help
    - rm -rf *
    - CC=/riscv/bin/riscv64-unknown-linux-gnu-gcc CXX=/riscv/bin/riscv64-unknown-linux-gnu-g++ cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_RISCV_DOCKER_PRESETS=ON -DUSE_OPENMP=ON -DINCLUDE_LUT_SUPPORT=OFF
    - make ${MAIN_NAME}
#    - src/${MAIN_NAME} --help
    - rm -rf *
    - CC=/riscv/bin/riscv64-unknown-linux-gnu-gcc CXX=/riscv/bin/riscv64-unknown-linux-gnu-g++ cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_RISCV_DOCKER_PRESETS=ON -DUSE_OPENMP=OFF -DINCLUDE_LUT_SUPPORT=OFF
    - make ${MAIN_NAME}
#    - src/${MAIN_NAME} --help
    - rm -rf *
  tags:
    - kubernetes

test: # Statically linked ${MAIN_NAME}${TEST_SUFFIX} has segmentation fault
  stage: test
  script:
    - mkdir build_test
    - cd build_test
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DUSE_RISCV_DOCKER_PRESETS=OFF -DUSE_OPENMP=ON -DINCLUDE_LUT_SUPPORT=OFF
    - make ${MAIN_NAME}${TEST_SUFFIX}
    - src/${MAIN_NAME}${TEST_SUFFIX}
    - rm -rf *
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DUSE_RISCV_DOCKER_PRESETS=OFF -DUSE_OPENMP=OFF -DINCLUDE_LUT_SUPPORT=OFF
    - make ${MAIN_NAME}${TEST_SUFFIX}
    - src/${MAIN_NAME}${TEST_SUFFIX}
    - rm -rf *
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_RISCV_DOCKER_PRESETS=OFF -DUSE_OPENMP=ON -DINCLUDE_LUT_SUPPORT=OFF
    - make ${MAIN_NAME}${TEST_SUFFIX}
    - src/${MAIN_NAME}${TEST_SUFFIX}
    - rm -rf *
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_RISCV_DOCKER_PRESETS=OFF -DUSE_OPENMP=OFF -DINCLUDE_LUT_SUPPORT=OFF
    - make ${MAIN_NAME}${TEST_SUFFIX}
    - src/${MAIN_NAME}${TEST_SUFFIX}
    - rm -rf *
  tags:
    - kubernetes

deploy:
  stage: deploy
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - mkdir build
    - mkdir release
    - cd build
    # x86_64, OpenMP On, LUT Off
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_RISCV_DOCKER_PRESETS=OFF -DUSE_OPENMP=ON -DINCLUDE_LUT_SUPPORT=OFF
    - make ${MAIN_NAME}
    - mv src/${MAIN_NAME} ../release/neuro-simulation_x86_64_omp_no_lut_${CI_JOB_ID}_${CI_COMMIT_TAG}
    - rm -rf *
    # x86_64, OpenMP Off, LUT Off
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_RISCV_DOCKER_PRESETS=OFF -DUSE_OPENMP=OFF -DINCLUDE_LUT_SUPPORT=OFF
    - make ${MAIN_NAME}
    - mv src/${MAIN_NAME} ../release/neuro-simulation_x86_64_no_omp_no_lut_${CI_JOB_ID}_${CI_COMMIT_TAG}
    - rm -rf *
    # riscv64, OpenMP On, LUT On
    - CC=/riscv/bin/riscv64-unknown-linux-gnu-gcc CXX=/riscv/bin/riscv64-unknown-linux-gnu-g++ cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_RISCV_DOCKER_PRESETS=ON -DUSE_OPENMP=ON -DINCLUDE_LUT_SUPPORT=ON
    - make ${MAIN_NAME}
    - mv src/${MAIN_NAME} ../release/neuro-simulation_riscv64_omp_lut_${CI_JOB_ID}_${CI_COMMIT_TAG}
    - rm -rf *
    # riscv64, OpenMP On, LUT Off
    - CC=/riscv/bin/riscv64-unknown-linux-gnu-gcc CXX=/riscv/bin/riscv64-unknown-linux-gnu-g++ cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_RISCV_DOCKER_PRESETS=ON -DUSE_OPENMP=ON -DINCLUDE_LUT_SUPPORT=OFF
    - make ${MAIN_NAME}
    - mv src/${MAIN_NAME} ../release/neuro-simulation_riscv64_omp_no_lut_${CI_JOB_ID}_${CI_COMMIT_TAG}
    - rm -rf *
    # riscv64, OpenMP Off, LUT On
    - CC=/riscv/bin/riscv64-unknown-linux-gnu-gcc CXX=/riscv/bin/riscv64-unknown-linux-gnu-g++ cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_RISCV_DOCKER_PRESETS=ON -DUSE_OPENMP=OFF -DINCLUDE_LUT_SUPPORT=ON
    - make ${MAIN_NAME}
    - mv src/${MAIN_NAME} ../release/neuro-simulation_riscv64_no_omp_lut_${CI_JOB_ID}_${CI_COMMIT_TAG}
    - rm -rf *
    # riscv64, OpenMP Off, LUT Off
    - CC=/riscv/bin/riscv64-unknown-linux-gnu-gcc CXX=/riscv/bin/riscv64-unknown-linux-gnu-g++ cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_RISCV_DOCKER_PRESETS=ON -DUSE_OPENMP=OFF -DINCLUDE_LUT_SUPPORT=OFF
    - make ${MAIN_NAME}
    - mv src/${MAIN_NAME} ../release/neuro-simulation_riscv64_no_omp_no_lut_${CI_JOB_ID}_${CI_COMMIT_TAG}
    - rm -rf *
  artifacts:
    paths:
      - release
  tags:
    - kubernetes
  only:
    - tags
