image: rhneuroprocessor/neuro-simulation-env:1.2.0

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - cd ..
    - cmake --build build --target main
  tags:
    - kubernetes-stage

test:
  stage: test
  script:
    - mkdir build_test
    - cd build_test
    - cmake ..
    - cd ..
    - cmake --build build_test --target main_test
    - build_test/src/main_test --gtest_filter=* --gtest_color=no
  tags:
    - kubernetes-stage
