image: docker:latest

# When using dind (Docker in Docker), it's wise to use the overlayfs driver for improved performance.
variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - docker info

build:
  stage: build
  before_script:
    # Build the docker image here
    - docker build -t runtime-env-image:latest .
  script:
    - docker run runtime-env-image:latest cmake --target main

test:
  stage: test
  script:
    - docker run runtime-env-image:latest cmake --target test
